/* The following code was generated by JFlex 1.6.0 */

/*
    CODE SECTION
*/
package Ph1;
import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>D:/Documents/Courses/Compiler Design/HW/Project/ALang/src/Ph1/lexer.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\17\1\20\1\20\1\17\22\0\1\60\2\0\1\4"+
    "\1\0\1\24\1\0\1\3\1\30\1\31\1\23\1\21\1\27\1\22"+
    "\1\5\1\16\12\2\1\26\1\25\1\36\1\40\1\37\2\0\32\1"+
    "\1\34\1\0\1\35\3\0\1\13\1\46\1\44\1\53\1\11\1\12"+
    "\1\50\1\45\1\41\2\1\1\14\1\51\1\42\1\43\1\47\1\1"+
    "\1\7\1\15\1\6\1\10\1\52\1\54\1\56\1\57\1\55\1\32"+
    "\1\0\1\33\7\0\1\20\u1fa2\0\1\20\1\20\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\6\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\13\1\3\0\1\26\12\0\1\27\1\30\1\31\1\32"+
    "\1\33\10\0\1\34\1\0\1\35\1\0\1\36\1\37"+
    "\1\40\4\0\1\41\3\0\1\42\2\0\1\43\17\0"+
    "\1\44\1\0\1\45\1\46\2\0\1\47\1\0\1\50"+
    "\11\0\1\51\3\0\1\52\1\53\1\54\5\0\1\55"+
    "\4\0\1\56\1\0\1\57\1\60\7\0\1\61\2\0"+
    "\1\62\1\63\1\0\1\64\1\0\1\65\1\0\1\66"+
    "\1\67\1\70\2\0\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\u0157"+
    "\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\61\0\61\0\61"+
    "\0\61\0\61\0\u027d\0\61\0\61\0\61\0\61\0\61"+
    "\0\61\0\61\0\u02ae\0\u02df\0\61\0\u0310\0\u0341\0\u0372"+
    "\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\u0498\0\u04c9\0\u04fa"+
    "\0\u052b\0\u055c\0\u058d\0\61\0\u05be\0\u05ef\0\u0620\0\u0651"+
    "\0\u0682\0\u06b3\0\u06e4\0\u0715\0\u0746\0\u0777\0\u07a8\0\61"+
    "\0\61\0\61\0\61\0\u07d9\0\u080a\0\u083b\0\u086c\0\u089d"+
    "\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25"+
    "\0\u052b\0\61\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\61\0\u0b1a"+
    "\0\u0b4b\0\u0b7c\0\61\0\u0bad\0\u0bde\0\61\0\u0c0f\0\u0c40"+
    "\0\u0c71\0\u0ca2\0\u0cd3\0\u0d04\0\u0d35\0\u0d66\0\u0d97\0\u0dc8"+
    "\0\u0df9\0\u0e2a\0\u0e5b\0\u0e8c\0\u0ebd\0\61\0\u0eee\0\61"+
    "\0\61\0\u0f1f\0\u0f50\0\61\0\u0f81\0\61\0\u0fb2\0\u0fe3"+
    "\0\u1014\0\u1045\0\u1076\0\u10a7\0\u10d8\0\u1109\0\u113a\0\61"+
    "\0\u116b\0\u119c\0\u11cd\0\61\0\61\0\61\0\u11fe\0\u122f"+
    "\0\u1260\0\u1291\0\u12c2\0\61\0\u12f3\0\u1324\0\u1355\0\u1386"+
    "\0\61\0\u13b7\0\61\0\61\0\u13e8\0\u1419\0\u144a\0\u147b"+
    "\0\u14ac\0\u14dd\0\u150e\0\61\0\u153f\0\u1570\0\61\0\61"+
    "\0\u15a1\0\61\0\u15d2\0\61\0\u1603\0\61\0\61\0\61"+
    "\0\u1634\0\u1665\0\61";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\2\2\1\15\1\2\1\0\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\2\1\40\1\2\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\2\2\1\50\1\2\63\0\1\3"+
    "\2\0\1\51\54\0\2\52\3\0\10\52\23\0\17\52"+
    "\2\0\1\53\4\0\10\53\23\0\17\53\6\0\1\54"+
    "\62\0\1\55\64\0\1\56\114\0\1\57\53\0\1\60"+
    "\13\0\1\61\15\0\1\62\1\63\26\0\1\64\57\0"+
    "\1\65\5\0\1\66\26\0\1\67\102\0\1\70\57\0"+
    "\1\71\1\72\60\0\1\73\62\0\1\74\31\0\1\75"+
    "\112\0\1\76\26\0\1\77\27\0\1\100\24\0\1\101"+
    "\114\0\1\102\60\0\1\103\30\0\1\104\56\0\1\105"+
    "\31\0\1\106\62\0\1\107\26\0\1\110\47\0\1\111"+
    "\61\0\1\112\56\0\1\113\4\0\10\113\23\0\17\113"+
    "\11\0\1\114\122\0\1\115\14\0\1\116\125\0\1\117"+
    "\46\0\1\120\33\0\1\121\107\0\1\122\24\0\1\123"+
    "\121\0\1\124\23\0\1\125\45\0\17\67\2\0\40\67"+
    "\6\0\1\126\122\0\1\127\23\0\1\130\122\0\1\131"+
    "\46\0\1\132\60\0\1\133\72\0\1\134\12\0\1\135"+
    "\121\0\1\136\7\0\1\137\12\0\1\140\122\0\1\141"+
    "\15\0\1\142\27\0\1\143\77\0\1\144\2\0\1\145"+
    "\67\0\1\146\110\0\1\147\62\0\1\150\23\0\1\151"+
    "\67\0\1\114\56\0\1\152\60\0\1\153\54\0\1\154"+
    "\116\0\1\155\22\0\1\156\121\0\1\157\24\0\1\160"+
    "\114\0\1\161\51\0\1\162\30\0\1\163\62\0\1\164"+
    "\60\0\1\165\60\0\1\166\107\0\1\167\60\0\1\170"+
    "\32\0\1\171\116\0\1\172\10\0\1\173\67\0\1\174"+
    "\55\0\1\175\117\0\1\176\54\0\1\177\32\0\1\200"+
    "\56\0\1\201\56\0\1\202\113\0\1\203\71\0\1\204"+
    "\14\0\1\205\113\0\1\206\26\0\1\207\56\0\1\210"+
    "\63\0\1\211\62\0\1\212\47\0\1\213\133\0\1\214"+
    "\20\0\1\215\56\0\1\216\60\0\1\217\56\0\1\220"+
    "\111\0\1\221\66\0\1\222\24\0\1\223\107\0\1\224"+
    "\65\0\1\225\55\0\1\226\55\0\1\227\67\0\1\230"+
    "\24\0\1\231\56\0\1\232\60\0\1\233\53\0\1\234"+
    "\65\0\1\235\53\0\1\236\117\0\1\237\60\0\1\240"+
    "\22\0\1\241\113\0\1\242\31\0\1\243\45\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5782];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\13\1\5\11\1\1\7\11\2\1\1\11"+
    "\13\1\3\0\1\11\12\0\1\1\4\11\10\0\1\1"+
    "\1\0\1\1\1\0\2\1\1\11\4\0\1\11\3\0"+
    "\1\11\2\0\1\11\17\0\1\11\1\0\2\11\2\0"+
    "\1\11\1\0\1\11\11\0\1\11\3\0\3\11\5\0"+
    "\1\11\4\0\1\11\1\0\2\11\7\0\1\11\2\0"+
    "\2\11\1\0\1\11\1\0\1\11\1\0\3\11\2\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public void echoFinding(String lexeme, String token, String attribute) throws IOException{
        FileWriter fw1 = new FileWriter("./src/Ph1/output.al", true);
        FileWriter fw2 = new FileWriter("./src/lexemes.al", true);
        BufferedWriter bw1 = new BufferedWriter(fw1);
        BufferedWriter bw2 = new BufferedWriter(fw2);
        String msg = lexeme + "\t\t" + token + "\t\t" + attribute;
        System.out.println(msg);
        bw1.write("\n"+msg);
        bw2.write("\n"+msg);
        bw1.close();
        bw2.close();
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Yytoken yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { 
          }
        case 58: break;
        case 2: 
          { echoFinding(yytext(), "ADADSABET", "-");
          }
        case 59: break;
        case 3: 
          { echoFinding(yytext(), "SINGLE_QUOTE_KW", "-");
          }
        case 60: break;
        case 4: 
          { echoFinding(yytext(), "DOT_KW", "-");
          }
        case 61: break;
        case 5: 
          { echoFinding(yytext(), "DIVIDE", "-");
          }
        case 62: break;
        case 6: 
          { echoFinding(yytext(), "PLUS", "-");
          }
        case 63: break;
        case 7: 
          { echoFinding(yytext(), "MINUS", "-");
          }
        case 64: break;
        case 8: 
          { echoFinding(yytext(), "MULTP", "-");
          }
        case 65: break;
        case 9: 
          { echoFinding(yytext(), "MOD", "-");
          }
        case 66: break;
        case 10: 
          { echoFinding(yytext(), "SEMICOLON_KW", "-");
          }
        case 67: break;
        case 11: 
          { echoFinding(yytext(), "COLON_KW", "-");
          }
        case 68: break;
        case 12: 
          { echoFinding(yytext(), "COMMA_KW", "-");
          }
        case 69: break;
        case 13: 
          { echoFinding(yytext(), "LP_KW", "-");
          }
        case 70: break;
        case 14: 
          { echoFinding(yytext(), "RP_KW", "-");
          }
        case 71: break;
        case 15: 
          { echoFinding(yytext(), "BLOCK_START", "-");
          }
        case 72: break;
        case 16: 
          { echoFinding(yytext(), "BLOCK_END", "-");
          }
        case 73: break;
        case 17: 
          { echoFinding(yytext(), "RANGE_START", "-");
          }
        case 74: break;
        case 18: 
          { echoFinding(yytext(), "RANGE_END", "-");
          }
        case 75: break;
        case 19: 
          { echoFinding(yytext(), "LT_KW", "-");
          }
        case 76: break;
        case 20: 
          { echoFinding(yytext(), "GT_KW", "-");
          }
        case 77: break;
        case 21: 
          { echoFinding(yytext(), "EQ_KW", "-");
          }
        case 78: break;
        case 22: 
          { echoFinding(yytext(), "TWO_DOTS_KW", "-");
          }
        case 79: break;
        case 23: 
          { echoFinding(yytext(), "COMMENTS", "-");
          }
        case 80: break;
        case 24: 
          { echoFinding(yytext(), "ASSIGN_KW", "-");
          }
        case 81: break;
        case 25: 
          { echoFinding(yytext(), "NEQ_KW", "-");
          }
        case 82: break;
        case 26: 
          { echoFinding(yytext(), "LTE_KW", "-");
          }
        case 83: break;
        case 27: 
          { echoFinding(yytext(), "GTE_KW", "-");
          }
        case 84: break;
        case 28: 
          { echoFinding(yytext(), "VA_KW", "-");
          }
        case 85: break;
        case 29: 
          { echoFinding(yytext(), "DO_KW", "-");
          }
        case 86: break;
        case 30: 
          { echoFinding(yytext(), "YA_KW", "-");
          }
        case 87: break;
        case 31: 
          { echoFinding(yytext(), "REALCONST", "-");
          }
        case 88: break;
        case 32: 
          { echoFinding(yytext(), "HARF", "-");
          }
        case 89: break;
        case 33: 
          { echoFinding(yytext(), "END_KW", "-");
          }
        case 90: break;
        case 34: 
          { echoFinding(yytext(), "FOR_KW", "-");
          }
        case 91: break;
        case 35: 
          { echoFinding(yytext(), "INT_KW", "-");
          }
        case 92: break;
        case 36: 
          { echoFinding(yytext(), "BOOLSABET", "-");
          }
        case 93: break;
        case 37: 
          { echoFinding(yytext(), "UPTO_KW", "-");
          }
        case 94: break;
        case 38: 
          { echoFinding(yytext(), "EXIT_KW", "-");
          }
        case 95: break;
        case 39: 
          { echoFinding(yytext(), "AGAR_KW", "-");
          }
        case 96: break;
        case 40: 
          { echoFinding(yytext(), "CHAR_KW", "-");
          }
        case 97: break;
        case 41: 
          { echoFinding(yytext(), "WHEN_KW", "-");
          }
        case 98: break;
        case 42: 
          { echoFinding(yytext(), "RAVIE_KW", "-");
          }
        case 99: break;
        case 43: 
          { echoFinding(yytext(), "FLOAT_KW", "-");
          }
        case 100: break;
        case 44: 
          { echoFinding(yytext(), "ANGAH_KW", "-");
          }
        case 101: break;
        case 45: 
          { echoFinding(yytext(), "MORED_KW", "-");
          }
        case 102: break;
        case 46: 
          { echoFinding(yytext(), "WHILE_KW", "-");
          }
        case 103: break;
        case 47: 
          { echoFinding(yytext(), "SHENASE", "-");
          }
        case 104: break;
        case 48: 
          { echoFinding(yytext(), "NAGHIZ_KW", "-");
          }
        case 105: break;
        case 49: 
          { echoFinding(yytext(), "DOWNTO_KW", "-");
          }
        case 106: break;
        case 50: 
          { echoFinding(yytext(), "BOOLEAN_KW", "-");
          }
        case 107: break;
        case 51: 
          { echoFinding(yytext(), "PROGRAM_KW", "-");
          }
        case 108: break;
        case 52: 
          { echoFinding(yytext(), "VAGARNA_KW", "-");
          }
        case 109: break;
        case 53: 
          { echoFinding(yytext(), "DEFAULT_KW", "-");
          }
        case 110: break;
        case 54: 
          { echoFinding(yytext(), "BAZGASHT_KW", "-");
          }
        case 111: break;
        case 55: 
          { echoFinding(yytext(), "GOZINESH_KW", "-");
          }
        case 112: break;
        case 56: 
          { echoFinding(yytext(), "VAANGAH_KW", "-");
          }
        case 113: break;
        case 57: 
          { echoFinding(yytext(), "YAVAGARNA_KW", "-");
          }
        case 114: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
